"""(add foreign key and relationship)

Revision ID: 040c36b0e084
Revises: 6b852562d3bf
Create Date: 2022-06-09 15:03:06.384169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c36b0e084'
down_revision = '6b852562d3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diskon_khusus',
    sa.Column('id_diskon_khusus', sa.Integer(), nullable=False),
    sa.Column('kode_diskon', sa.String(length=10), nullable=False),
    sa.Column('nama_diskon', sa.String(length=200), nullable=True),
    sa.Column('besaran_diskon', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_diskon_khusus'),
    sa.UniqueConstraint('kode_diskon')
    )
    op.create_table('kategori',
    sa.Column('id_kategori', sa.Integer(), nullable=False),
    sa.Column('kode_kategori', sa.String(length=10), nullable=False),
    sa.Column('nama_kategori', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_kategori'),
    sa.UniqueConstraint('kode_kategori')
    )
    op.create_table('satuan',
    sa.Column('id_satuan', sa.Integer(), nullable=False),
    sa.Column('satuan', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_satuan'),
    sa.UniqueConstraint('satuan')
    )
    op.create_table('barang',
    sa.Column('id_barang', sa.Integer(), nullable=False),
    sa.Column('kode_barang', sa.String(length=10), nullable=False),
    sa.Column('nama_barang', sa.String(length=255), nullable=False),
    sa.Column('satuan', sa.String(length=10), nullable=False),
    sa.Column('harga_jual', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('harga_beli', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.Column('diskon', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_kategori', sa.Integer(), nullable=True),
    sa.Column('id_satuan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.ForeignKeyConstraint(['id_satuan'], ['satuan.id_satuan'], ),
    sa.PrimaryKeyConstraint('id_barang'),
    sa.UniqueConstraint('kode_barang'),
    sa.UniqueConstraint('nama_barang'),
    sa.UniqueConstraint('satuan')
    )
    op.create_table('penjualan',
    sa.Column('id_penjualan', sa.Integer(), nullable=False),
    sa.Column('kode_penjualan', sa.String(length=10), nullable=False),
    sa.Column('tanggal_penjualan', sa.DateTime(), nullable=True),
    sa.Column('jumlah_penjualan', sa.Integer(), nullable=True),
    sa.Column('total_pembayaran', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_penjualan'),
    sa.UniqueConstraint('kode_penjualan')
    )
    op.create_table('grosir',
    sa.Column('id_grosir', sa.Integer(), nullable=False),
    sa.Column('min_jumlah', sa.Integer(), nullable=True),
    sa.Column('harga_grosir', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_barang', sa.Integer(), nullable=True),
    sa.Column('id_kategori', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.PrimaryKeyConstraint('id_grosir')
    )
    op.create_table('supplier',
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('nama_supplier', sa.String(length=255), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('terjual', sa.Integer(), nullable=True),
    sa.Column('sisa', sa.Integer(), nullable=True),
    sa.Column('harga_satuan', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('harga_total', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('tanggal_taruh', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_barang', sa.Integer(), nullable=True),
    sa.Column('id_kategori', sa.Integer(), nullable=True),
    sa.Column('id_satuan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.ForeignKeyConstraint(['id_satuan'], ['satuan.id_satuan'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_supplier'),
    sa.UniqueConstraint('nama_supplier')
    )
    op.create_table('detail_penjualan',
    sa.Column('id_detail_penjualan', sa.Integer(), nullable=False),
    sa.Column('no_urut', sa.Integer(), nullable=True),
    sa.Column('jumlah_barang', sa.Integer(), nullable=True),
    sa.Column('total_harga', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_barang', sa.Integer(), nullable=True),
    sa.Column('id_penjualan', sa.Integer(), nullable=True),
    sa.Column('id_diskon_khusus', sa.Integer(), nullable=True),
    sa.Column('id_grosir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ),
    sa.ForeignKeyConstraint(['id_diskon_khusus'], ['diskon_khusus.id_diskon_khusus'], ),
    sa.ForeignKeyConstraint(['id_grosir'], ['grosir.id_grosir'], ),
    sa.ForeignKeyConstraint(['id_penjualan'], ['penjualan.id_penjualan'], ),
    sa.PrimaryKeyConstraint('id_detail_penjualan')
    )
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id_category', sa.INTEGER(), nullable=False),
    sa.Column('category_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('category_code')
    )
    op.drop_table('detail_penjualan')
    op.drop_table('supplier')
    op.drop_table('grosir')
    op.drop_table('penjualan')
    op.drop_table('barang')
    op.drop_table('satuan')
    op.drop_table('kategori')
    op.drop_table('diskon_khusus')
    # ### end Alembic commands ###
