"""(add table vendor in change of supplier)

Revision ID: 4d20b23d5e64
Revises: 1cd08f58b1c6
Create Date: 2022-06-20 10:28:21.035028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d20b23d5e64'
down_revision = '1cd08f58b1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id_vendor', sa.Integer(), nullable=False),
    sa.Column('nama_vendor', sa.String(length=255), nullable=True),
    sa.Column('nama_barang', sa.String(length=255), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.Column('terjual', sa.Integer(), nullable=True),
    sa.Column('sisa', sa.Integer(), nullable=True),
    sa.Column('harga_satuan', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('harga_total', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True),
    sa.Column('tanggal_taruh', sa.DateTime(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_kategori', sa.Integer(), nullable=True),
    sa.Column('id_satuan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], name=op.f('fk_vendor_id_kategori_kategori')),
    sa.ForeignKeyConstraint(['id_satuan'], ['satuan.id_satuan'], name=op.f('fk_vendor_id_satuan_satuan')),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], name=op.f('fk_vendor_id_user_user')),
    sa.PrimaryKeyConstraint('id_vendor', name=op.f('pk_vendor'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    # ### end Alembic commands ###
