"""(add tanggal_masuk in barang)

Revision ID: 598eea074ff4
Revises: 4d20b23d5e64
Create Date: 2022-06-20 16:53:54.415100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598eea074ff4'
down_revision = '4d20b23d5e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_masuk', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('tanggal_masuk')

    # ### end Alembic commands ###
