"""(change nullable user)

Revision ID: 6910dde4885f
Revises: dad5b8445547
Create Date: 2022-06-14 14:56:15.427137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6910dde4885f'
down_revision = 'dad5b8445547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('join_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('join_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
