"""(add stok akhir tabel barang)

Revision ID: 6b12f7a6ac27
Revises: 9a3d688447fd
Create Date: 2022-07-01 10:02:29.630580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b12f7a6ac27'
down_revision = '9a3d688447fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stok_akhir', sa.Integer(), nullable=True))

    with op.batch_alter_table('detail_penjualan', schema=None) as batch_op:
        batch_op.drop_constraint('fk_detail_penjualan_id_grosir_grosir', type_='foreignkey')
        batch_op.drop_column('diskon_khusus')
        batch_op.drop_column('id_grosir')

    with op.batch_alter_table('grosir', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_grosir', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True))
        batch_op.alter_column('id_grosir',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grand_total', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjualan', schema=None) as batch_op:
        batch_op.drop_column('grand_total')

    with op.batch_alter_table('grosir', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('id_grosir',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('harga_grosir')

    with op.batch_alter_table('detail_penjualan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_grosir', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('diskon_khusus', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_detail_penjualan_id_grosir_grosir', 'grosir', ['id_grosir'], ['id_grosir'])

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('stok_akhir')

    # ### end Alembic commands ###
