"""(add column grosir to barang)

Revision ID: 9a3d688447fd
Revises: b9fe05bc4e01
Create Date: 2022-06-30 11:07:57.068339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3d688447fd'
down_revision = 'b9fe05bc4e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_grosir', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('harga_grosir', sa.Float(precision=20, asdecimal=True, decimal_return_scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('harga_grosir')
        batch_op.drop_column('jumlah_grosir')

    # ### end Alembic commands ###
