"""(add more column to detail_penjualan)

Revision ID: 9a860dd27dff
Revises: 726075a3fb69
Create Date: 2022-06-21 11:07:47.502567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a860dd27dff'
down_revision = '726075a3fb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_penjualan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_kembalian', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ppn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_penjualan', schema=None) as batch_op:
        batch_op.drop_column('ppn')
        batch_op.drop_column('jumlah_kembalian')

    # ### end Alembic commands ###
