"""(drop table penjualan dan detail penjualan)

Revision ID: d851a8d150ac
Revises: 9a860dd27dff
Create Date: 2022-06-30 09:12:14.887913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd851a8d150ac'
down_revision = '9a860dd27dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_penjualan')
    op.drop_table('penjualan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjualan',
    sa.Column('id_penjualan', sa.INTEGER(), nullable=False),
    sa.Column('kode_penjualan', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tanggal_penjualan', sa.DATETIME(), nullable=True),
    sa.Column('jumlah_penjualan', sa.INTEGER(), nullable=True),
    sa.Column('total_pembayaran', sa.FLOAT(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_penjualan'),
    sa.UniqueConstraint('kode_penjualan', name='uq_penjualan_kode_penjualan')
    )
    op.create_table('detail_penjualan',
    sa.Column('id_detail_penjualan', sa.INTEGER(), nullable=False),
    sa.Column('no_urut', sa.INTEGER(), nullable=True),
    sa.Column('jumlah_barang', sa.INTEGER(), nullable=True),
    sa.Column('total_harga', sa.FLOAT(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=False),
    sa.Column('updated_date', sa.DATETIME(), nullable=True),
    sa.Column('id_barang', sa.INTEGER(), nullable=True),
    sa.Column('id_penjualan', sa.INTEGER(), nullable=True),
    sa.Column('id_diskon_khusus', sa.INTEGER(), nullable=True),
    sa.Column('id_grosir', sa.INTEGER(), nullable=True),
    sa.Column('jumlah_bayar', sa.INTEGER(), nullable=True),
    sa.Column('sub_total', sa.INTEGER(), nullable=True),
    sa.Column('potongan', sa.INTEGER(), nullable=True),
    sa.Column('diskon_khusus', sa.INTEGER(), nullable=True),
    sa.Column('jumlah_kembalian', sa.INTEGER(), nullable=True),
    sa.Column('ppn', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id_barang'], ),
    sa.ForeignKeyConstraint(['id_diskon_khusus'], ['diskon_khusus.id_diskon_khusus'], ),
    sa.ForeignKeyConstraint(['id_grosir'], ['grosir.id_grosir'], ),
    sa.ForeignKeyConstraint(['id_penjualan'], ['penjualan.id_penjualan'], ),
    sa.PrimaryKeyConstraint('id_detail_penjualan')
    )
    # ### end Alembic commands ###
